server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html index.htm;

    location /mod-ledger/ {
        # Try to serve file directly, fallback to index.html for SPA routing
        try_files $uri $uri/ /index.html;
    }
    # This default location catches all other requests and serves from root
    location / {
        try_files $uri $uri/ /index.html;
    }
}